name: KaiToDo
options:
  bundleIdPrefix: com.kaitodo
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  developmentLanguage: en

settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"

targets:
  KaiToDo:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - "*.yml"
          - "*.md"
          - ".git/**"
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: KaiToDo.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.kaitodo.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        DEVELOPMENT_TEAM: ""
    entitlements:
      path: KaiToDo.entitlements
      properties:
        aps-environment: development
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.kaitodo.app
        com.apple.developer.icloud-services:
          - CloudKit

schemes:
  KaiToDo:
    build:
      targets:
        KaiToDo: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
